### ISSUE TITLE
autokey should be an informative, not normative reference (or removed entirely)

### ISSUE THREAD

**Issue by samuelweiler** [hstenn/ietf-ntp-i-do#4]
Autokey is only mentioned for historical context - that makes it an informative reference, not normative.  It's not even clear that the historical mention is helpful, though....

**Comment by hstenn** [comment]
There are other drafts that are informative - all the new EF proposals.  How should I cite those?

**Comment by hstenn** [comment]
And there's nothing intrinsically wrong with sending an I-DO that includes Autokey.   Not that people should be using autokey, but if somebody *wants* to support it, it's perfectly acceptable to put that in an I-DO message.
